### ISSUE TITLE
consultation......

### ISSUE THREAD

**Issue by hs805430** [WangStephen/DL-limited-angle-CT-reconstruction#1]
王老师您好，我是一名大四学生，最近正在学习深度学习应用于CT图像重建的相关知识，在阅读了您在国际医学与生物工程年会的会议文章之后，在GitHub上下载了您的代码并尝试运行，但是出现了错误如下:No such file or directory : "normalized_ct_phantoms/phantom_1.npy";并且我发现我下载的代码文件里面的没有相应的.npy文件。（似乎并非仅仅缺少这一个文件）；我正在用心阅读您的文章和代码，还希望您能抽空帮我解答一下，非常感谢，祝您身体健康，万事如意。

     Dear Mr. Wang, I am a senior student, and I am learning about the application of deep learning in CT image reconstruction recently. After reading your article in Annual International Conference Of  EMBC , I have downloaded your code from GitHub and tried to run it, but there was an error as follows : No such file or directory: "normalized_ct_phantoms/phantom_1.npy"; 
     And I certainly found that there is no corresponding ".npy " file in the code zip file I downloaded ; I am reading your article and code with my heart, and I hope you can spare some time to help me answer it. Thank you very much. I wish you good health and all the best.

**Comment by WangStephen** [comment]
你好，很抱歉之前一直没有上GitHub，现在才回复，希望你一切还顺利。这个phantom的npy文件数据我没有上传，因为有20个而且文件大小也有点大。你可以参考[这个网站](https://www.ircad.fr/research/3d-ircadb-01/)。我的原始的20个ct数据就是来源这个网站，然后我对这些原始的ct进行了一些预处理然后生成了对应的phantom的npy文件。祝好。
